### ISSUE TITLE
Generated Builtin Types const methods not compiling 

### ISSUE THREAD

**Issue by Des-Nerger** [thimenesup/GodotZigBindings#13]
When trying to call `.slice()`, I get this:
```
src/gen/builtin_classes/packed_string_array.zig:188:44: error: @ptrCast discards const qualifier
        gd.callBuiltinMbNoRet(binds.slice, @ptrCast(&self._opaque), .{ &p_begin_encoded, &p_end_encoded });
                                           ^~~~~~~~~~~~~~~~~~~~~~~
src/gen/builtin_classes/packed_string_array.zig:188:44: note: use @constCast to discard const qualifier
```
___
As an API design sidenote: in [godot-rust they provide `PackedStringArray::{as_slice,as_mut_slice}`](https://godot-rust.github.io/docs/gdext/master/godot/prelude/struct.PackedStringArray.html#method.as_slice) methods to return a native Rust slice directly, so that a user could subslice and do further operations without crossing the costly FFI boundary. Rust's and Zig's slices are very similar, so I thought a similar thing could be made here as well. Although, it goes a bit against the Godot convention: godot-rust had to rename the Godot's former `.slice()` to `.subarray()`.

**Comment by thimenesup** [comment]
This is an issue in three, one which is a bug, the other two are not implemented stuff, which only one is core behaviour. 
The actual issue is fixed by 344f0e8, open another issue for generated builtin types implementing operators.
