### ISSUE TITLE
Add Usage Example/Instructions

### ISSUE THREAD

**Issue by desttinghim** [thimenesup/GodotZigBindings#2]
From the README it isn't clear how to consume the generated bindings. My first thought was that `lib.zig` exported all the core and generated types. Looking at `lib.zig` reveals it is a gdnative script instead. Is the intended usage that you copy the bindings to your own project? If so, this would be useful to mention in the README.

**Comment by thimenesup** [comment]
3d03ac4 should have made more obvious how you can use this library.
