### ISSUE TITLE
`Input.getSingleton()`?

### ISSUE THREAD

**Issue by Des-Nerger** [thimenesup/GodotZigBindings#8]
I started to rewrite the Godot 4.0 version of the Dodge The Creeps game into Zig, but stumbled upon the lack of `Input.getSingleton()`. I guess, for the time being we have to do something along the lines of `gd.interface.?.global_get_singleton.?(...)`, right?

**Comment by thimenesup** [comment]
Fixed by 
7d1bdf7.
